version: '3'

tasks:
  default:
    dir: admin
    cmds:
      - NODE_OPTIONS=--openssl-legacy-provider npm run build

  initdb:
    cmds:
    - docker run --rm -v ${PWD}:/data --name tpl -p 5432:5432 -e POSTGRES_PASSWORD=testus -d postgres:15-alpine
    - until docker exec tpl pg_isready ; do sleep 1 ; done
    - sleep 1
    - docker exec tpl createdb -U postgres templates

  db:
    cmds:
    - usql postgresql://postgres:testus@172.17.0.1/templates

  up:
    dir: admin
    cmds:
      - npm update

  build:
    cmds:
      - CGO_ENABLED=0 go build -tags netgo -ldflags '-w -X main.version={{.GIT_TAG}}' -o fashion
    vars:
      GIT_TAG:
        sh: git describe --tags
    
  deploy:
    deps: [build]
    cmds:
      - rsync -avzz fashion web fashion:fashion/
      - ssh auspicious systemctl restart fashion.service
